default: &default
  adapter: redis
  url: <%= ENV["REDIS_URL"] %>
  channel_prefix: quickstart_<%= Rails.env %>

development:
  <<: *default

test:
  adapter: test

staging:
  <<: *default

production:
  <<: *default
